import fs from 'node:fs/promises';
const files={
'package.json':JSON.stringify({name:'wama-frontend',version:'1.0.0',private:true,scripts:{dev:'next dev',build:'next build',start:'next start',lint:'eslint .',typecheck:'tsc --noEmit',qa:'node scripts/qa.mjs'},dependencies:{next:'^16.2.0',react:'^19.2.0','react-dom':'^19.2.0',gsap:'^3.14.0',lenis:'^1.3.0'},devDependencies:JSON.parse(await fs.readFile('package.json','utf8')).devDependencies},null,2),
 'tsconfig.json':JSON.stringify({compilerOptions:{target:'ES2017',lib:['dom','dom.iterable','esnext'],allowJs:true,skipLibCheck:true,strict:true,noEmit:true,esModuleInterop:true,module:'esnext',moduleResolution:'bundler',resolveJsonModule:true,isolatedModules:true,jsx:'react-jsx',incremental:true,plugins:[{name:'next'}],paths:{'@/*':['./src/*']}},include:['next-env.d.ts','**/*.ts','**/*.tsx','.next/types/**/*.ts','.next/dev/types/**/*.ts'],exclude:['node_modules']},null,2),
 'next-env.d.ts':'/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n',
 'postcss.config.mjs':'export default { plugins: { "@tailwindcss/postcss": {} } };\n',
 'eslint.config.mjs':'import { defineConfig, globalIgnores } from "eslint/config";\nimport next from "eslint-config-next/core-web-vitals";\nimport ts from "eslint-config-next/typescript";\nexport default defineConfig([...next,...ts,globalIgnores([".next/**","docs/**","next-env.d.ts"])]);\n',
 'next.config.ts':'import type { NextConfig } from "next";\nconst config: NextConfig = { poweredByHeader: false, images: { formats: ["image/avif", "image/webp"] } };\nexport default config;\n',
 '.gitignore':'node_modules/\n.next/\n.env*\n!.env.example\n*.tsbuildinfo\n',
 '.env.example':'NEXT_PUBLIC_SITE_URL=http://localhost:3000\n# Optional owned form destination. Without it, the form prepares an email draft.\nNEXT_PUBLIC_CONTACT_EMAIL=comercial@wama.digital\n',
 'src/data/site.ts':`export const site = { name: 'Wama', title: 'Wama | Agência de Design, Sites, SaaS e Aplicativos', description: 'Design e desenvolvimento de produtos digitais. Sites, sistemas e aplicativos construídos com design de excelência.', url: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000', email: process.env.NEXT_PUBLIC_CONTACT_EMAIL || 'comercial@wama.digital', reference: 'https://wama.com.br', navigation: [{label:'clientes',href:'/#clientes'},{label:'projetos',href:'/#cases'},{label:'serviços',href:'/#services'},{label:'sobre',href:'/#big-numbers'},{label:'blog',href:'https://wama.com.br/blog'}] };\n`,
 'src/app/layout.tsx':`import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { site } from '@/data/site';
import { MotionController } from '@/animations/MotionController';
import './globals.css';
const lausanne = localFont({ src: [{path:'../assets/lausanne-regular.woff2',weight:'400',style:'normal'},{path:'../assets/lausanne-light.woff2',weight:'200',style:'normal'}], variable:'--font-lausanne', display:'swap', fallback:['Arial'],adjustFontFallback:'Arial' });
export const metadata: Metadata = { metadataBase:new URL(site.url), title:{default:site.title,template:'%s | Wama'}, description:site.description,alternates:{canonical:'/'},openGraph:{title:site.title,description:site.description,url:'/',siteName:site.name,locale:'pt_BR',type:'website',images:[{url:'/opengraph-image.jpg',width:1200,height:630,alt:'Wama — Design e desenvolvimento de produtos digitais'}]},twitter:{card:'summary_large_image',title:site.title,description:site.description,images:['/opengraph-image.jpg']},robots:{index:true,follow:true},icons:{icon:'/icon.svg'} };
export default function RootLayout({children}:{children:React.ReactNode}) { return <html lang="pt-BR" className={lausanne.variable}><body><a href="#main" className="skip-link">Pular para o conteúdo</a>{children}<MotionController /></body></html>; }
`,
 'src/components/layout/Header.tsx':`'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { site } from '@/data/site';
export function Header(){const [open,setOpen]=useState(false);const toggle=useRef<HTMLButtonElement>(null);const panel=useRef<HTMLDivElement>(null);
useEffect(()=>{if(!open)return;const prior=document.body.style.overflow;document.body.style.overflow='hidden';panel.current?.querySelector<HTMLAnchorElement>('a')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus();}if(e.key==='Tab'){const focusable=[...panel.current!.querySelectorAll<HTMLAnchorElement>('a'),toggle.current!];const i=focusable.indexOf(document.activeElement as HTMLAnchorElement);e.preventDefault();focusable[(i+(e.shiftKey?-1:1)+focusable.length)%focusable.length]?.focus();}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=prior;document.removeEventListener('keydown',key);};},[open]);
const links=site.navigation.map(n=><Link onClick={()=>setOpen(false)} className="nav-link" href={n.href} key={n.label}><span>{n.label}</span><span aria-hidden="true">{n.label}</span></Link>);
return <header className={"site-header "+(open?"menu-open":"")}><nav className="shell flex items-center justify-between" aria-label="Navegação principal"><Link href="/#hero" className="brand" aria-label="Wama — início" onClick={()=>setOpen(false)}>wama<sup>®</sup></Link><div className="desktop-nav flex items-center">{links}</div><div className="header-actions flex items-center"><Link className="button" href="/#contato" onClick={()=>setOpen(false)}><span className="desktop-label">Inicie um projeto</span><span className="mobile-label">Orçamento</span></Link><button ref={toggle} type="button" className="menu-toggle" aria-expanded={open} aria-controls="mobile-menu" aria-label={open?'Fechar menu':'Abrir menu'} onClick={()=>setOpen(!open)}><span/><span/></button></div></nav><div ref={panel} id="mobile-menu" className="mobile-menu" hidden={!open}>{links}</div></header>;
}
`,
 'src/components/sections/Hero.tsx':`import Image from 'next/image';
import type { CSSProperties } from 'react';
import content from '@/data/content.json';
export function Hero(){return <section id="hero" className="hero"><div className="shell hero-copy"><h1>Design e desenvolvimento de produtos digitais</h1><p>Uma nova geração de sites, sistemas e aplicativos construídos com design de excelência, valor e sempre superando as expectativas</p></div><div className="shell hero-visual"><div className="fan-stage" aria-label="Projetos digitais selecionados"><div className="fan-cards">{content.hero.map((card,i)=><div className="fan-card" key={card.src} style={{'--angle':(-52.75+i*12.5)+'deg',zIndex:35+i*50} as CSSProperties}><Image src={card.src} alt={['Projeto Visor','Projeto Pepper','Projeto Vibra','Projeto Wiz Benefícios','Projeto Camila Farani','Projeto KFC Brasil','Projeto Tera','Projeto Royal Enfield'][i]} fill sizes="(max-width:809px) 110px, 300px" priority={i>=2&&i<=6} draggable={false}/></div>)}</div></div></div></section>}
`,
 'src/animations/MotionController.tsx':`'use client';
import { useEffect } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
export function MotionController(){useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{const lenis=new Lenis({smoothWheel:true,syncTouch:false,duration:1.05,anchors:{offset:-80}});lenis.on('scroll',ScrollTrigger.update);const tick=(time:number)=>lenis.raf(time*1000);gsap.ticker.add(tick);
const fan=document.querySelector<HTMLElement>('.fan-cards');if(fan){gsap.to(fan,{rotation:12.5,duration:9,repeat:-1,yoyo:true,ease:'sine.inOut'});}
return()=>{gsap.ticker.remove(tick);lenis.destroy();};});return()=>mm.revert();},[]);return null;}
`,
 'src/app/page.tsx':`import { Header } from '@/components/layout/Header';\nimport { Hero } from '@/components/sections/Hero';\nexport default function Home(){return <><Header/><main id="main"><Hero/></main></>;}\n`,
 'public/icon.svg':'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="16"/><text x="32" y="44" text-anchor="middle" fill="white" font-family="Arial" font-size="46">w</text></svg>',
 'src/app/globals.css':`@import "tailwindcss";
:root{--background:#fff;--foreground:#000;--muted:#555;--border:#d0ccdf;--surface:#101010;--container-max:1400px;--section-space:160px;--space-xs:8px;--space-sm:16px;--space-md:24px;--space-lg:40px;--space-xl:56px;--space-2xl:80px;--radius-sm:6px;--radius-md:10px;--radius-lg:100px}
@theme inline{--color-background:var(--background);--color-foreground:var(--foreground);--font-sans:var(--font-lausanne);--breakpoint-md:810px;--breakpoint-xl:1200px}
*{box-sizing:border-box}html{scroll-padding-top:80px}body{margin:0;background:var(--background);color:var(--foreground);font-family:var(--font-lausanne),Arial,sans-serif;font-weight:400;-webkit-font-smoothing:antialiased}a{color:inherit;text-decoration:none}button,input,textarea{font:inherit}button,a,input,textarea{touch-action:manipulation}button{cursor:pointer}h1,h2,h3,p,figure{margin:0}h1,h2,h3{font-weight:400;letter-spacing:-.01em}h2{font-size:56px;line-height:1.2}p{line-height:1.5}img{object-fit:cover}button:focus-visible,a:focus-visible,input:focus-visible,textarea:focus-visible,summary:focus-visible{outline:2px solid #7272ff;outline-offset:5px}.shell{width:90%;max-width:var(--container-max);margin-inline:auto}.section{padding-block:var(--section-space)}.skip-link{position:fixed;top:8px;left:8px;z-index:999;background:white;padding:12px;transform:translateY(-160%)}.skip-link:focus{transform:none}.button{display:inline-flex;align-items:center;justify-content:center;background:#000;color:#fff;border-radius:100px;padding:7px 24px 8px;font-size:16px;line-height:24px;white-space:nowrap;transition:background .2s,color .2s}.button:hover{background:#333}.site-header{position:fixed;inset:0 0 auto;z-index:500;background:white;padding-block:20px;transition:background .25s,color .25s}.brand{font-size:28px;line-height:1;letter-spacing:-1.5px}.brand sup{font-size:6px;letter-spacing:0;position:relative;top:-12px;margin-left:1px}.desktop-nav{gap:32px}.nav-link{height:24px;position:relative;overflow:hidden;font-size:20px;line-height:24px}.nav-link span{display:block;transition:transform .3s}.nav-link:hover span{transform:translateY(-100%)}.header-actions{gap:24px}.menu-toggle,.mobile-label{display:none}.mobile-menu[hidden]{display:none}.hero{padding:156px 0 160px;overflow:hidden}.hero-copy{display:flex;flex-direction:column;align-items:center;text-align:center;gap:20px}.hero h1{font-size:72px;line-height:1.1;max-width:900px}.hero-copy p{font-size:20px;line-height:30px;max-width:600px}.hero-visual{margin-top:64px;aspect-ratio:2.11765;background:#f7f7f7;position:relative}.fan-stage,.fan-cards{position:absolute;inset:0}.fan-stage{overflow:hidden}.fan-cards{transform-origin:50% 205%}.fan-card{position:absolute;left:50%;top:11%;height:67%;aspect-ratio:.62;transform:translateX(-50%) rotate(var(--angle));transform-origin:50% 290%;border-radius:10px;box-shadow:-28px 8px 40px #00000059;overflow:hidden;backface-visibility:hidden}.fan-card img{pointer-events:none;user-select:none}.site-header.is-dark{background:#000;color:#fff}.site-header.is-dark .button{background:white;color:#000}.site-header.is-hidden{transform:translateY(-110%)}
@media(max-width:1199px){:root{--section-space:80px}h2{font-size:32px}.desktop-nav{display:none}.menu-toggle{display:flex;position:relative;width:32px;height:32px;border:0;background:none;color:inherit;flex-direction:column;justify-content:center;gap:8px}.menu-toggle span{width:32px;height:2px;background:currentColor;transition:transform .3s}.menu-open .menu-toggle span:first-child{transform:translateY(5px) rotate(45deg)}.menu-open .menu-toggle span:last-child{transform:translateY(-5px) rotate(-45deg)}.mobile-label{display:inline}.desktop-label{display:none}.mobile-menu{padding:56px 5%;display:flex;flex-direction:column;gap:26px;height:calc(100dvh - 64px);background:inherit}.mobile-menu .nav-link{font-size:40px;line-height:48px;height:48px;width:max-content}.hero{padding:104px 0 0}.hero h1{font-size:48px}.hero-visual{width:100%;max-width:none;margin-top:24px}}
@media(max-width:809px){:root{--section-space:56px}h2{font-size:28px}.site-header{padding:12px 0}.site-header .shell{width:calc(100% - 26px)}.site-header .button{font-size:14px;line-height:21px;padding:6px 24px}.hero{padding:96px 0 64px}.hero-copy{align-items:flex-start;text-align:left;gap:12px}.hero h1{font-size:36px;line-height:1.1}.hero-copy p{font-size:14px;line-height:21px;max-width:360px}.hero-visual{margin-top:64px;height:121px;aspect-ratio:auto;background:transparent}.fan-stage{height:350px;top:-62px;overflow:visible}.fan-cards{transform-origin:50% 150%}.fan-card{height:48%;border-radius:6px}.header-actions{gap:24px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*::before,*::after{animation-duration:.01ms!important;transition-duration:.01ms!important}}
`};
for(const [file,body]of Object.entries(files)){await fs.mkdir(file.split('/').slice(0,-1).join('/')||'.',{recursive:true});await fs.writeFile(file,body);}
console.log('Header and hero implemented.');
